name: Update Manifest

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run getlatest.py to update manifest.json
        run: python getlatest.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
    
      - name: Commit and push changes if any
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add manifest.json
            git commit -m "Update manifest.json [skip ci]"
            git push origin gh-pages
          else
            echo "No changes detected. Skipping commit."
          fi
